[package]
name = "b"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
a = { path = "../a", default-features = false }

[target.'cfg(target = "BOGUS-TARGET-NAME")'.dependencies]
a = { path = "../a", features = ["fail"] }
